### ISSUE TITLE
manifest corrupted (field 'comparer') want 'leveldb.BytewiseComparator', got 'idb_cmp1'

### ISSUE THREAD

**Issue by rustyx** [psanford/leveldb-dump#3]
It seems the Chromium's IndexedDB format isn't supported because of a custom comparer

```
$ leveldb-dump .config/Slack/IndexedDB/https_app.slack.com_0.indexeddb.leveldb
2024/01/04 15:47:19 open db err: leveldb: manifest corrupted (field 'comparer'): mismatch: want 'leveldb.BytewiseComparator', got 'idb_cmp1' [file=MANIFEST-000001]
```

It would be good to add support for `idb_cmp1`.

**Comment by psanford** [comment]
Looks like someone has written one in Go already: https://github.com/cions/leveldb-cli/blob/master/indexeddb/comparer.go

I'd take a PR to add support for this.
